name: Fund_ZFB

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 20 3,6 * * MON-FRI

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        # 选择要使用的 node 版本
        node-version:'16'

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
      
    - name: working
      env:
        CORPID: ${{secrets.CORPID}}
        AGENTID: ${{secrets.CTID}}
        CORPSECRET: ${{secrets.CTSECRET}}
        TOUSER: ${{secrets.TOUSER}}
        MEDIA: ${{secrets.CTMEDIA}}
      run:
        python3 ./code/ZFB_Fund.py