name: Fund_ZFB

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 20 3,6 * * MON-FRI

jobs:
  run-tool:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Run py
      env:
        CORPID: ${{secrets.CORPID}}
        AGENTID: ${{secrets.CTID}}
        CORPSECRET: ${{secrets.CTSECRET}}
        TOUSER: ${{secrets.TOUSER}}
        MEDIA: ${{secrets.CTMEDIA}}
      run: |
        python3 ./code/ZFB_Fund.py > run_log.txt

    - name: Upload log
      uses: actions/upload-artifact@v3
      with:
        name: log
        path: run_log.txt
        retention-days: 3
    
    - name: Display log
      uses: actions/download-artifact@v3
      with:
        name: log