name: Fund_ZFB

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 20 3,6 * * MON-FRI

jobs:
  run-tool:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - run: pip install -r requirements.txt
    - run: pip test

    - name: working
      env:
        CORPID: ${{secrets.CORPID}}
        AGENTID: ${{secrets.CTID}}
        CORPSECRET: ${{secrets.CTSECRET}}
        TOUSER: ${{secrets.TOUSER}}
        MEDIA: ${{secrets.CTMEDIA}}
      run:
        python3 ./code/ZFB_Fund.py