name: Fund_ZFB

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 20 3,6 * * MON-FRI

jobs:
  checkin:
    runs-on: ubuntu-latest
    container: node:16.16.0

    steps:
    - uses: actions/checkout@v3

    - name: Upload artifacts
	    uses: actions/upload-artifact@v3
	    with:
		    name: public
		    path: public
		    retention-days: 3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
      
    - name: working
      env:
        CORPID: ${{secrets.CORPID}}
        AGENTID: ${{secrets.CTID}}
        CORPSECRET: ${{secrets.CTSECRET}}
        TOUSER: ${{secrets.TOUSER}}
        MEDIA: ${{secrets.CTMEDIA}}
      run:
        python ./code/ZFB_Fund.py