name: Invest_Fund

on:
  workflow_dispatch:
  schedule:
    - cron: 20 3,6 * * MON-FRI

jobs:
  run-tool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      
      - name: Working
        env:
          CORPID: ${{secrets.CORPID}}
          AGENTID: ${{secrets.CTID}}
          CORPSECRET: ${{secrets.CTSECRET}}
          MEDIA: ${{secrets.CTMEDIA}}
          TOUSER: ${{secrets.TOUSER}}
        run: 
          python3 ./code/Invest_Fund.py
