name: 手机壁纸

on: 
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      
      - name: Working
        env:
          KEY1: ${{secrets.KEY1}}
        run: 
          python ./code/Mobile_wallpaper.py
