name: OnSite_Fund

on:
  workflow_dispatch:
  schedule:
    - cron: 55 13 * * MON-FRI

jobs:
  run-tool:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      
      - name: Working
        env:
          CORPID: ${{secrets.CORPID}}
          AGENTID: ${{secrets.CTID}}
          CORPSECRET: ${{secrets.CTSECRET}}
          TOUSER: ${{secrets.TOUSER}}
          MEDIA: ${{secrets.CTMEDIA}}
        run: 
          python3 ./code/OnSite_Fund.py
