name: 天翼云盘

on: 
  workflow_dispatch:
  schedule:
    - cron: '22 22  *  *  *'

jobs:
  run-tool:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      
      - name: Working
        env:
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
          CORPID: ${{secrets.CORPID}}
          AGENTID: ${{secrets.AGENTID}}
          CORPSECRET: ${{secrets.CORPSECRET}}
          TOUSER: ${{secrets.TOUSER}}
          MEDIA: ${{secrets.MEDIA}}
        run: 
          python ./code/TY_Pan.py
