name: ZFB_Fund

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 20 3,6 * * MON-FRI

jobs:
  checkin:
    runs-on: ubuntu-latest
    container: node:16.16.0

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements.txt
      
    - name: working
      env:
        CORPID: ${{secrets.CORPID}}
        AGENTID: ${{secrets.CTID}}
        CORPSECRET: ${{secrets.CTSECRET}}
        TOUSER: ${{secrets.TOUSER}}
        MEDIA: ${{secrets.CTMEDIA}}
      run:
        python ./code/ZFB_Fund.py