#工作名字
name: ZFB_Fund

on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: 20 3,6 * * MON-FRI

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      
      - name: Checkin
        run: |
          python ./code/ZFB_Fund.py
       
  env:
  #设置环节变量
    CORPID: ${{secrets.CORPID}}
    AGENTID: ${{secrets.CTID}}
    CORPSECRET: ${{secrets.CTSECRET}}
    TOUSER: ${{secrets.TOUSER}}
    MEDIA: ${{secrets.CTMEDIA}}
