name: ZFB_Fund

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '02 02 03,06 * * MON-FRI *'

jobs:
  run-tool:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      
      - name: Working
        env:
          CORPID: ${{secrets.CORPID}}
          AGENTID: ${{secrets.CTID}}
          CORPSECRET: ${{secrets.CTSECRET}}
          TOUSER: ${{secrets.TOUSER}}
          MEDIA: ${{secrets.CTMEDIA}}
        run: 
          python ./code/ZFB_Fund.py
